sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: m/eTqdC6fSDYxQZkpHJ2/mBIio8ynWd5x/nZyY70nxOYaEhW+7p2ApoBzYHVZkbcS1yJlYyYHAErBPEAXX/+vY0a8nfn37WKwMdRBcCg550GAWTfjjjFRhE3CAWc9Cw6swlklROnEddvZXTCfT9chJ+oDS6fvihC8pZa3Ut8hi1OxGRegXmoQrNEPEu/JLnkYiD1qg2qGrKWk8v7nFbZx+iIOjqYb5zB7k7PDnqY5ZLL09wUC2CHFUen/sD8EMFpxhwGyWRsVCOjJitvasQwT8FyoYbEmGKc0cKqlrD1ZWqgfKsDx0xGb5cXIX8i2584LY0kjnLDbpKrDbNqJRAK8cVkuikqteHPQDB39xinMylNfMzV8D0WZ/h1e0QM0y8douryLnl2jACyDt0PU3A3ATzH5a88werBgoPWID/JWekfaHRQvisnpEdZSOiyFyJdBiT1wY5EGrc2tUnpPoqN1kx83RyqAqjCbarW3nDjyFdbt/nXw+z9qmG33skxCwRQpj8/YcYmSjdcPz7ZG17UpdBwTtV7mc0Wobyldq38Fpv+ElzdrpZzw6U9z4sKchN7TqV3ZRrvymtqXULTV+cEpxaphqy2dwUGRnQFD7JZrpFh1YwSfo5W01gNxmemRVjojZzieR0LNvS1h93QLhlNcK3grTKXShnj3Au/WTZ4TIg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Devil-s-Disciple_3638
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy